inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - features/step_definitions/**/*
    - lib/tasks/**/*
