default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: consent
  password: password
  pool: 5

development:
  <<: *default
  database: consent


test:
  <<: *default
  database: consent_test
